default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME")  %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>

development:
  <<: *default
  database: app_to_do_list_development

test:
  <<: *default
  database: app_to_do_list_test

production:
  <<: *default
  database: app_to_do_list_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>
